<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <style>
        a { color: inherit; }
        a:hover { text-decoration: none; color: inherit; }

        .navbar {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .province-text {
            border-radius: 5px;
            font-size: 35px;
            padding: 10px 0 10px 0;
        }
        .province-text:hover {
            background-color: #e5e5e5;
            cursor: pointer;
        }
    </style>
</head>

<body>
<nav class="navbar" style="border-radius: 0">
    <div class="navbar-header">
        <span class="navbar-brand">Hospital - Provinces List</span>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h2>说明</h2>
            <p>点击省份名称查看医院列表</p>
        </div>
    </div>
    <div class="row">
        {% for province in provinces %}
        <div class="col-md-3 text-center province-text">
            <span>
                <a href="{{ provinces[province]['pinyin'] }}.html">{{ province }}</a>
            </span>
        </div>
        {% endfor %}
    </div>
    <hr>
    <footer>
        <p>Hospital</p>
    </footer>
</div>

</body>
</html>
