<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <style>
        .navbar-header .navbar-brand a {
            color: #eeeeee;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-inverse" style="border-radius: 0">
    <div class="navbar-header">
        <span class="navbar-brand">医院列表 - {{ province }}</span>
        <span class="navbar-brand"><a href="hospitals.html">返回城市列表</a></span>
    </div>
</nav>

<div class="container">
    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>医院名称</th>
                    <th>医院类型</th>
                    <th>负责人</th>
                    <th>地址</th>
                    <th>更多</th>
                </tr>
            </thead>
            <tbody>
                {% for hospital in hospitals %}
                <tr>
                    <td>{{ hospitals[hospital]['name'] }}</td>
                    <td>{{ hospitals[hospital]['type'] }}</td>
                    <td>{{ hospitals[hospital]['principal'] }}</td>
                    <td>{{ hospitals[hospital]['address'] }}</td>
                    <td><a data-toggle="collapse" href="#collapse{{ loop.index }}">点击查看...</a></td>
                </tr>
                <tr id="collapse{{ loop.index }}" class="collapse"><td colspan="5">
                    <div>名称: {{ hospital }}</div>
                    <div>负责人: {{ hospitals[hospital]["principal"] }}</div>
                    <div>省: {{ hospitals[hospital]["province"] }}</div>
                    <div>市: {{ hospitals[hospital]["city"] }}</div>
                    <div>地址: {{ hospitals[hospital]["address"] }}</div>
                    <div>类型: {{ hospitals[hospital]["type"] }}</div>
                    <div>网址:
                    {% for url in hospitals[hospital]["url"] %}
                        {{ url }} &nbsp;
                    {% endfor %}
                    </div>
                    <div>备注: {{ hospitals[hospital]["note"] }}</div>
                </td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
    <footer>
        <p>本页面信息遵循<a href="https://github.com/open-power-workgroup/Hospital/blob/incoming/open_data_usage_license.md" target="_blank" rel="noopener noreferrer">OPW开放数据使用授权协议</a>发布</p>
    </footer>
</div>
</body>
</html>
